### ISSUE TITLE
Utils unit test

### ISSUE THREAD

**Issue by H01001000** [discordeno/discordeno#2689]
```[tasklist]
### Tasks
- [ ] https://github.com/discordeno/discordeno/issues/2793
- [ ] https://github.com/discordeno/discordeno/issues/2796
- [ ] https://github.com/discordeno/discordeno/issues/2802
- [ ] https://github.com/discordeno/discordeno/issues/2797
- [ ] test(utils): more test for colors.ts
- [ ] test(utils): more test for files.ts
- [x] test(utils): more test for hash.ts
- [ ] https://github.com/discordeno/discordeno/issues/2827
- [ ] test(utils): more test for index.ts
- [ ] test(utils): more test for logger.ts
- [x] test(utils): more test for permission.ts
- [ ] https://github.com/discordeno/discordeno/issues/2826
- [x] test(utils): more test for urlToBase64.ts
- [ ] https://github.com/discordeno/discordeno/issues/2799
- [ ] https://github.com/discordeno/discordeno/issues/2828
```

**Comment by Skillz4Killz** [comment]
@H01001000 if u get time to make the utils reach 100% otherwise lets close this out
