### ISSUE TITLE
v19 Release Checklist

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#2789]
```[tasklist]
### Tasks

- [ ] https://github.com/discordeno/discordeno/issues/2790
- [ ] https://github.com/discordeno/discordeno/issues/2791
- [ ] https://github.com/discordeno/discordeno/issues/2822
- [ ] https://github.com/discordeno/discordeno/issues/2821
- [ ] https://github.com/discordeno/discordeno/issues/2820
- [ ] https://github.com/discordeno/discordeno/issues/2815
- [ ] https://github.com/discordeno/discordeno/issues/2814
- [ ] https://github.com/discordeno/discordeno/issues/2819
- [ ] https://github.com/discordeno/discordeno/issues/2818
- [ ] https://github.com/discordeno/discordeno/issues/2817
- [ ] https://github.com/discordeno/discordeno/issues/2813
- [ ] https://github.com/discordeno/discordeno/issues/2812
- [ ] https://github.com/discordeno/discordeno/issues/2816
```
