### ISSUE TITLE
[Docs]: Improve contribution docs

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3169]
```[tasklist]
### Tasks
- [ ] https://github.com/discordeno/discordeno/issues/3170
- [ ] https://github.com/discordeno/discordeno/issues/3171
- [ ] https://github.com/discordeno/discordeno/issues/3172
- [ ] https://github.com/discordeno/discordeno/issues/3174
- [ ] https://github.com/discordeno/discordeno/issues/3175
- [ ] https://github.com/discordeno/discordeno/issues/3176
- [ ] https://github.com/discordeno/discordeno/issues/3179
- [x] List technology we use (Turborepo, etc), I don't think this is needed actually?
- [ ] https://github.com/discordeno/discordeno/issues/3162
```

```[tasklist]
### Spec
- [x] Contributor could know repo layout
- [x] Contributor could know dev tools
- [x] Contributor could know how to test
- [x] Contributor could know how to pr
```

**Comment by AwesomeStickz** [comment]
v19 is released and we only have one of these tasks pending, which is in its own issue in #3175 so closing this
