### ISSUE TITLE
[Docs]: Improve user docs and example

### ISSUE THREAD

**Issue by AwesomeStickz** [discordeno/discordeno#3273]
```[tasklist]
### Tasks
- [x] Fix big bot docs
- [x] Move things that weren't moved from old docs to new olds and remove old docs
```

```[tasklist]
### Spec
- [x] Beginner guide minimal
- [x] Big bot guide minimal
- [x] API guide (not API reference)
- [x] Showcase (how to integrate in prod system)
```
