### ISSUE TITLE
Discordeno v11 Roadmap

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#823]
# Remaining To Do List

- [x] rewrite the typings
- [x] Voice functionality #16 
- [x] Complete coverage of unit tests
- [x] Slash in dm #583 
- [x] Functions return collections #670 
- [x] Validate name utility function #702 
- [x] Validate length of string function
- [x] Rewrite boiler/template for v11 support slash commands in gateway
- [x] Create a slash boiler/template for webhook style with deno deploy
- [x] Automate 16x sharding at 100k #793 
- [x] Rewrite the guide website in v11
- [x] Separate the guide to the other repo and use that repo on the website mod.land
- [x] Finish all `//TODO:` comments
- [x] Support for stage channels
- [x] WS request queue #836
- [x] Review all the prs night closed and see what changes need to be made. He closed a shit ton of prs
- [x] Remove guild template structure
- [x] Application Command Perms #857
- [x] Discovery Settings #853
- [x] Check Nonce limits #851
- [x] Add Search Members #850
- [x] Add Welcome Screen Endpoints #849
- [x] Better directory structure #864
